##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.7.1] date: [Tue Jan 19 00:20:15 CST 2021]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = robot_chassis


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build
GCC_PATH  = ./toolchain/gcc-arm-none-eabi-8-2018-q4-major/bin

######################################
# source
######################################
# C sources
C_SOURCES =  \
Application/Robotchissis/Src/main.c \
Application/Robotchissis/Src/stm32g4xx_hal_msp.c \
Application/Robotchissis/Src/peripherals.c \
Application/Robotchissis/Src/systicks.c \
Application/Robotchissis/Src/communicate.c \
Application/Robotchissis/Src/system_stm32g4xx.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_utils.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_exti.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_adc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cordic.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_crc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_crc_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fdcan.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fmac.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_i2c.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_i2c_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_dac.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_comp.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_opamp.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_spi.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_usart.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_tim.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_rcc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_pwr.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_ucpd.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_gpio.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_dma.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c \
OS/threadx/common/src/tx_block_allocate.c \
OS/threadx/common/src/tx_block_pool_cleanup.c \
OS/threadx/common/src/tx_block_pool_create.c \
OS/threadx/common/src/tx_block_pool_delete.c \
OS/threadx/common/src/tx_block_pool_info_get.c \
OS/threadx/common/src/tx_block_pool_initialize.c \
OS/threadx/common/src/tx_block_pool_performance_info_get.c \
OS/threadx/common/src/tx_block_pool_performance_system_info_get.c \
OS/threadx/common/src/tx_block_pool_prioritize.c \
OS/threadx/common/src/tx_block_release.c \
OS/threadx/common/src/tx_byte_allocate.c  \
OS/threadx/common/src/tx_byte_pool_cleanup.c \
OS/threadx/common/src/tx_byte_pool_create.c \
OS/threadx/common/src/tx_byte_pool_delete.c \
OS/threadx/common/src/tx_byte_pool_info_get.c \
OS/threadx/common/src/tx_byte_pool_initialize.c \
OS/threadx/common/src/tx_byte_pool_performance_info_get.c \
OS/threadx/common/src/tx_byte_pool_performance_system_info_get.c \
OS/threadx/common/src/tx_byte_pool_prioritize.c \
OS/threadx/common/src/tx_byte_pool_search.c \
OS/threadx/common/src/tx_byte_release.c \
OS/threadx/common/src/tx_event_flags_cleanup.c \
OS/threadx/common/src/tx_event_flags_create.c \
OS/threadx/common/src/tx_event_flags_delete.c \
OS/threadx/common/src/tx_event_flags_get.c \
OS/threadx/common/src/tx_event_flags_info_get.c \
OS/threadx/common/src/tx_event_flags_initialize.c \
OS/threadx/common/src/tx_event_flags_performance_info_get.c \
OS/threadx/common/src/tx_event_flags_performance_system_info_get.c \
OS/threadx/common/src/tx_event_flags_set.c \
OS/threadx/common/src/tx_event_flags_set_notify.c \
OS/threadx/common/src/tx_initialize_high_level.c \
OS/threadx/common/src/tx_initialize_kernel_enter.c \
OS/threadx/common/src/tx_initialize_kernel_setup.c \
OS/threadx/common/src/tx_misra.c \
OS/threadx/common/src/tx_mutex_cleanup.c \
OS/threadx/common/src/tx_mutex_create.c \
OS/threadx/common/src/tx_mutex_delete.c \
OS/threadx/common/src/tx_mutex_get.c \
OS/threadx/common/src/tx_mutex_info_get.c \
OS/threadx/common/src/tx_mutex_initialize.c \
OS/threadx/common/src/tx_mutex_performance_info_get.c \
OS/threadx/common/src/tx_mutex_performance_system_info_get.c \
OS/threadx/common/src/tx_mutex_prioritize.c \
OS/threadx/common/src/tx_mutex_priority_change.c \
OS/threadx/common/src/tx_mutex_put.c \
OS/threadx/common/src/tx_queue_cleanup.c \
OS/threadx/common/src/tx_queue_create.c \
OS/threadx/common/src/tx_queue_delete.c \
OS/threadx/common/src/tx_queue_flush.c \
OS/threadx/common/src/tx_queue_front_send.c \
OS/threadx/common/src/tx_queue_info_get.c \
OS/threadx/common/src/tx_queue_initialize.c \
OS/threadx/common/src/tx_queue_performance_info_get.c \
OS/threadx/common/src/tx_queue_performance_system_info_get.c \
OS/threadx/common/src/tx_queue_prioritize.c \
OS/threadx/common/src/tx_queue_receive.c \
OS/threadx/common/src/tx_queue_send.c \
OS/threadx/common/src/tx_queue_send_notify.c \
OS/threadx/common/src/tx_semaphore_ceiling_put.c \
OS/threadx/common/src/tx_semaphore_cleanup.c \
OS/threadx/common/src/tx_semaphore_create.c \
OS/threadx/common/src/tx_semaphore_delete.c \
OS/threadx/common/src/tx_semaphore_get.c \
OS/threadx/common/src/tx_semaphore_info_get.c \
OS/threadx/common/src/tx_semaphore_initialize.c \
OS/threadx/common/src/tx_semaphore_performance_info_get.c \
OS/threadx/common/src/tx_semaphore_performance_system_info_get.c \
OS/threadx/common/src/tx_semaphore_prioritize.c \
OS/threadx/common/src/tx_semaphore_put.c \
OS/threadx/common/src/tx_semaphore_put_notify.c \
OS/threadx/common/src/tx_thread_create.c \
OS/threadx/common/src/tx_thread_delete.c \
OS/threadx/common/src/tx_thread_entry_exit_notify.c \
OS/threadx/common/src/tx_thread_identify.c \
OS/threadx/common/src/tx_thread_info_get.c \
OS/threadx/common/src/tx_thread_initialize.c \
OS/threadx/common/src/tx_thread_performance_info_get.c \
OS/threadx/common/src/tx_thread_performance_system_info_get.c \
OS/threadx/common/src/tx_thread_preemption_change.c \
OS/threadx/common/src/tx_thread_priority_change.c \
OS/threadx/common/src/tx_thread_relinquish.c \
OS/threadx/common/src/tx_thread_reset.c \
OS/threadx/common/src/tx_thread_resume.c \
OS/threadx/common/src/tx_thread_shell_entry.c \
OS/threadx/common/src/tx_thread_sleep.c \
OS/threadx/common/src/tx_thread_stack_analyze.c \
OS/threadx/common/src/tx_thread_stack_error_handler.c \
OS/threadx/common/src/tx_thread_stack_error_notify.c \
OS/threadx/common/src/tx_thread_suspend.c \
OS/threadx/common/src/tx_thread_system_preempt_check.c \
OS/threadx/common/src/tx_thread_system_resume.c \
OS/threadx/common/src/tx_thread_system_suspend.c \
OS/threadx/common/src/tx_thread_terminate.c \
OS/threadx/common/src/tx_thread_time_slice.c \
OS/threadx/common/src/tx_thread_time_slice_change.c \
OS/threadx/common/src/tx_thread_timeout.c \
OS/threadx/common/src/tx_thread_wait_abort.c \
OS/threadx/common/src/tx_time_get.c \
OS/threadx/common/src/tx_time_set.c \
OS/threadx/common/src/tx_timer_activate.c \
OS/threadx/common/src/tx_timer_change.c \
OS/threadx/common/src/tx_timer_create.c \
OS/threadx/common/src/tx_timer_deactivate.c \
OS/threadx/common/src/tx_timer_delete.c \
OS/threadx/common/src/tx_timer_expiration_process.c \
OS/threadx/common/src/tx_timer_info_get.c \
OS/threadx/common/src/tx_timer_initialize.c \
OS/threadx/common/src/tx_timer_performance_info_get.c \
OS/threadx/common/src/tx_timer_performance_system_info_get.c \
OS/threadx/common/src/tx_timer_system_activate.c \
OS/threadx/common/src/tx_timer_system_deactivate.c \
OS/threadx/common/src/tx_timer_thread_entry.c \
OS/threadx/common/src/tx_trace_buffer_full_notify.c \
OS/threadx/common/src/tx_trace_disable.c \
OS/threadx/common/src/tx_trace_enable.c \
OS/threadx/common/src/tx_trace_event_filter.c \
OS/threadx/common/src/tx_trace_event_unfilter.c \
OS/threadx/common/src/tx_trace_initialize.c \
OS/threadx/common/src/tx_trace_interrupt_control.c \
OS/threadx/common/src/tx_trace_isr_enter_insert.c \
OS/threadx/common/src/tx_trace_isr_exit_insert.c \
OS/threadx/common/src/tx_trace_object_register.c \
OS/threadx/common/src/tx_trace_object_unregister.c \
OS/threadx/common/src/tx_trace_user_event_insert.c \
OS/threadx/common/src/txe_block_allocate.c \
OS/threadx/common/src/txe_block_pool_create.c \
OS/threadx/common/src/txe_block_pool_delete.c \
OS/threadx/common/src/txe_block_pool_info_get.c \
OS/threadx/common/src/txe_block_pool_prioritize.c \
OS/threadx/common/src/txe_block_release.c \
OS/threadx/common/src/txe_byte_allocate.c \
OS/threadx/common/src/txe_byte_pool_create.c \
OS/threadx/common/src/txe_byte_pool_delete.c \
OS/threadx/common/src/txe_byte_pool_info_get.c \
OS/threadx/common/src/txe_byte_pool_prioritize.c \
OS/threadx/common/src/txe_byte_release.c \
OS/threadx/common/src/txe_event_flags_create.c \
OS/threadx/common/src/txe_event_flags_delete.c \
OS/threadx/common/src/txe_event_flags_get.c \
OS/threadx/common/src/txe_event_flags_info_get.c \
OS/threadx/common/src/txe_event_flags_set.c \
OS/threadx/common/src/txe_event_flags_set_notify.c \
OS/threadx/common/src/txe_mutex_create.c \
OS/threadx/common/src/txe_mutex_delete.c \
OS/threadx/common/src/txe_mutex_get.c \
OS/threadx/common/src/txe_mutex_info_get.c \
OS/threadx/common/src/txe_mutex_prioritize.c \
OS/threadx/common/src/txe_mutex_put.c \
OS/threadx/common/src/txe_queue_create.c \
OS/threadx/common/src/txe_queue_delete.c \
OS/threadx/common/src/txe_queue_flush.c \
OS/threadx/common/src/txe_queue_front_send.c \
OS/threadx/common/src/txe_queue_info_get.c \
OS/threadx/common/src/txe_queue_prioritize.c \
OS/threadx/common/src/txe_queue_receive.c \
OS/threadx/common/src/txe_queue_send.c \
OS/threadx/common/src/txe_queue_send_notify.c \
OS/threadx/common/src/txe_semaphore_ceiling_put.c \
OS/threadx/common/src/txe_semaphore_create.c \
OS/threadx/common/src/txe_semaphore_delete.c \
OS/threadx/common/src/txe_semaphore_get.c \
OS/threadx/common/src/txe_semaphore_info_get.c \
OS/threadx/common/src/txe_semaphore_prioritize.c \
OS/threadx/common/src/txe_semaphore_put.c \
OS/threadx/common/src/txe_semaphore_put_notify.c \
OS/threadx/common/src/txe_thread_create.c \
OS/threadx/common/src/txe_thread_delete.c \
OS/threadx/common/src/txe_thread_entry_exit_notify.c \
OS/threadx/common/src/txe_thread_info_get.c \
OS/threadx/common/src/txe_thread_preemption_change.c \
OS/threadx/common/src/txe_thread_priority_change.c \
OS/threadx/common/src/txe_thread_relinquish.c \
OS/threadx/common/src/txe_thread_reset.c \
OS/threadx/common/src/txe_thread_resume.c \
OS/threadx/common/src/txe_thread_suspend.c \
OS/threadx/common/src/txe_thread_terminate.c \
OS/threadx/common/src/txe_thread_time_slice_change.c \
OS/threadx/common/src/txe_thread_wait_abort.c \
OS/threadx/common/src/txe_timer_activate.c \
OS/threadx/common/src/txe_timer_change.c \
OS/threadx/common/src/txe_timer_create.c \
OS/threadx/common/src/txe_timer_deactivate.c \
OS/threadx/common/src/txe_timer_delete.c \
OS/threadx/common/src/txe_timer_info_get.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/bus_voltage_sensor.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/circle_limitation.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/digital_output.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/flux_weakening_ctrl.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/motor_power_measurement.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/ntc_temperature_sensor.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/open_loop.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/pid_regulator.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/pqd_motor_power_measurement.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/pwm_curr_fdbk.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/pwm_common.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/r_divider_bus_voltage_sensor.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/ramp_ext_mngr.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/revup_ctrl.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/speed_pos_fdbk.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/speed_torq_ctrl.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/state_machine.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/sto_pll_speed_pos_fdbk.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/virtual_bus_voltage_sensor.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Src/virtual_speed_sensor.c \
Middlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/G4xx/Src/r3_2_g4xx_pwm_curr_fdbk.c \
Middlewares/Utilities/Src/packet.c \
Middlewares/Utilities/Src/utilities.c \
Middlewares/Device/Src/ahrs.c \
Middlewares/Device/Src/as5600.c \
Middlewares/Device/Src/icm20602.c \
Middlewares/Device/Src/imu_calibration.c \
Middlewares/Device/Src/mpu6050.c \
Middlewares/Device/Src/tle5012b.c \
Framework/Foc/Src/mc_api.c \
Framework/Foc/Src/mc_config.c \
Framework/Foc/Src/mc_interface.c \
Framework/Foc/Src/mc_math.c \
Framework/Foc/Src/mc_parameters.c \
Framework/Foc/Src/mc_tasks.c \
Framework/Foc/Src/motorcontrol.c \
Framework/Foc/Src/regular_conversion_manager.c 



# ASM sources
ASM_SOURCES =  \
startup_stm32g431xx.s

ASM_OS_SOURCE = \
OS/threadx/ports/cortex_m4/gnu/src/tx_initialize_low_level.S \
OS/threadx/ports/cortex_m4/gnu/src/tx_thread_context_restore.S \
OS/threadx/ports/cortex_m4/gnu/src/tx_thread_context_save.S \
OS/threadx/ports/cortex_m4/gnu/src/tx_thread_interrupt_control.S \
OS/threadx/ports/cortex_m4/gnu/src/tx_thread_schedule.S \
OS/threadx/ports/cortex_m4/gnu/src/tx_thread_stack_build.S \
OS/threadx/ports/cortex_m4/gnu/src/tx_thread_system_return.S \
OS/threadx/ports/cortex_m4/gnu/src/tx_timer_interrupt.S


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_FULL_LL_DRIVER \
-DUSE_HAL_DRIVER \
-DSTM32G431xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IApplication/Robotchissis/Inc \
-IDrivers/STM32G4xx_HAL_Driver/Inc \
-IDrivers/STM32G4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32G4xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/CMSIS/Include \
-IMiddlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/Any/Inc \
-IMiddlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/MCLib/G4xx/Inc \
-IMiddlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/UILibrary/Inc \
-IMiddlewares/MCSDK_v5.4.4-Full/MotorControl/MCSDK/SystemDriveParams \
-IMiddlewares/Utilities/Inc \
-IMiddlewares/Device/Inc \
-IFramework/Foc/Inc \
-IOS/threadx/ports/cortex_m4/gnu/inc \
-IOS/threadx/common/inc \
-IThirdParty/eigen



# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32G431VBTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_OS_SOURCE:.S=.o)))
vpath %.S $(sort $(dir $(ASM_OS_SOURCE)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
